### ISSUE TITLE
App crashes if scene(_:willConnectTo:options:) contains a different common setup

### ISSUE THREAD

**Issue by filippopassante** [openbakery/InstanceHelper#1]
The test test_window_is_created_on_willConnectTo() causes my app to crash with message "Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)" if the scene delegate contains the following common programmatic setup:
```
guard let windowScene = (scene as? UIWindowScene) else { return }
window = UIWindow(frame: windowScene.coordinateSpace.bounds)
window?.windowScene = windowScene
window?.rootViewController = UINavigationController(rootViewController: ViewController())
window?.makeKeyAndVisible()
```

I get this on a plain project that I've just added the instance helper files to and removed the storyboard from.

Substituting the above implementation with the one portrayed on GitHub solves the issue.

**Comment by renep** [comment]
Have you disable the Thread and Address Sanitizer?

**Comment by filippopassante** [comment]
Hi René,

Thank you for your code and for your prompt reply.

I think they are off:
<img width="444" alt="Screenshot 2023-12-06 alle 16 22 24" src="https://github.com/openbakery/InstanceHelper/assets/40905965/6b449a52-c77d-4783-b683-9feb9a3cf9a6">

Here is the project if there's anything else you need to know: https://drive.google.com/drive/folders/1YjYVf9Nd5MedzihOgNsQFuSLAFsyuz7q?usp=share_link

**Comment by renep** [comment]
Create the window using this line then it works: 
```
window = UIWindow(windowScene: windowScene)
```

**Comment by filippopassante** [comment]
Right. Thank you very much
